version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-static:/usr/share/nginx/html
    networks:
      - app-network
  backend-1:
    image: onuryurteri/instazam-backend:1.2
    ports:
      - "8080:8080"
    networks:
      - app-network

  instazam-python:
    image: onuryurteri/instazam-python:1.1
    ports:
      - "8000:8000"
    volumes:
      - ./nginx-static/converted:/src/converted

  db_mongo:
    image: mongo
    volumes:
      - ./.mongo/volume:/data/db
    ports:
      - "27017-27019:27017-27019"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge